language: node_js
node_js:
  - 12
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

before_script:
  - psql -c 'create database test_db;' -U postgres
  - npm run build
  - npm install -g sequelize-cli
  - NODE_ENV=test npx sequelize-cli db:migrate
  - NODE_ENV=test npx sequelize-cli db:seed:all
script:
  - NODE_ENV=test npm test
after_success:
  - NODE_ENV=test npm run test:coverage
  