language: node_js
node_js:
  - 12
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database resources_recommendation_test_db;' -U postgres
  - psql -c "CREATE USER sege WITH PASSWORD null;" -U postgres
  - npm run build
  - npm install -g sequelize-cli
  - NODE_ENV=test npm run pretest
script:
  - NODE_ENV=test npm test
after_success:
  - NODE_ENV=test npm run test:coverage
  